
version: '2'

services:
  pg-master:
    build: '.'
    image: 'hoteltonight/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    ports:
    - '7432:5432'
    expose:
     - '5432'

  pg-slave:
    build: '.'
    image: 'hoteltonight/postgres-replication'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/var/lib/postgresql/data'
    ports:
    - '7433:5432'
    expose:
     - '5432'
    links:
     - 'pg-master'
